version: '3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'internship-program'
      MYSQL_USER: '@dm1nUser11'
      MYSQL_PASSWORD: 'us3rp@ssw0rD12'
      MYSQL_ROOT_PASSWORD: 's0m3s3cr3t1ntr13'
    ports:
      - '3310:3306'
    volumes:
      - internship-storage:/var/lib/mysql

volumes:
  internship-storage: