version: '3'

services:
  internship-program-ui-prod:
    build: ./internship-program-frontend
    ports:
      - '4300:80'
    depends_on:
      - internship-program-api-prod
  internship-program-api-prod:
    build: ./internship-program-backend
    restart: on-failure
    ports:
      - '8085:8080'
    depends_on:
      - internship-program-db-prod
  internship-program-db-prod:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'internship-program'
      MYSQL_USER: '@dm1nUser11'
      MYSQL_PASSWORD: 'us3rp@ssw0rD12'
      MYSQL_ROOT_PASSWORD: 's0m3s3cr3t1ntr13'
    ports:
      - '3310:3306'
    volumes:
      - internship-storage:/var/lib/mysql

volumes:
  internship-storage:
